<a href="https://colab.research.google.com/github/pranavishal/Pytorch-CNN/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.4.1+cu121


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

## Creating Tensors


In [4]:
# scalar, PyTorch tensors are created by torch.tensor(x)
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim # number of dimensions

0

In [6]:
scalar.item() # get tensor back as a python int

7

In [7]:
# vector

In [8]:
vector = torch.tensor([7, 7])
vector.ndim
vector.shape


torch.Size([2])

In [9]:
vector.ndim

1

In [10]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
##TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [16]:
TENSOR[0].shape

torch.Size([3, 3])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR2 = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]],
                        [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

In [19]:
TENSOR2.shape

torch.Size([2, 3, 3])



```
# This is formatted as code
```

### Random Tensors

Why Random tensors

random tensors are important because the way many neural networks learn is that they start with tensors full of randm numbers and then adjust those random numbers to better represent the data

start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers


In [20]:
# Create a random tensor of shape(3, 4)

random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.5848, 0.7128, 0.4516, 0.6098],
         [0.8488, 0.7541, 0.1262, 0.4288],
         [0.4519, 0.5082, 0.6038, 0.9351]],

        [[0.0828, 0.1300, 0.9988, 0.3067],
         [0.4973, 0.0100, 0.7810, 0.5219],
         [0.0118, 0.4833, 0.4878, 0.5507]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([2, 3, 4])

In [23]:
#Create a random tensor with similar shape ot an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [24]:
### Zeros and ones

In [25]:
# Create a tensor of all zeros
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zero * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [27]:
#all ones tensor

ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
random_tensor.dtype

torch.float32

In [30]:
# create a rang of tensors and tensors-like

#use torch.range()
one_to_ten = torch.arange(0, 10)
one_to_1000 = torch.arange(start=1, end=1000, step=92)

In [31]:
one_to_1000

tensor([  1,  93, 185, 277, 369, 461, 553, 645, 737, 829, 921])

In [32]:
#tensors like
ten_zeros = torch.zeros_like(input=one_to_1000)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
flt_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32, device=None, requires_grad=False)
#dtype what data type is the tensor made of
#device what device is your tensor on
#whether or not tot rack gradients with this tensors operations
flt_tensor

tensor([3., 6., 9.])

In [34]:
flt_tensor.dtype

torch.float32

In [35]:
#Tensor Datatypes
#tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning
#1. Tensors not right datatype
#2. Tensors not right shape
#3. Tensors not on the right device

In [36]:
float_16_tensor = flt_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
int_32_tensor * flt_tensor

tensor([ 9., 36., 81.])

In [39]:
flt_tensor

tensor([3., 6., 9.])

### Getting information from tensors (Tensor Attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [40]:
flt_tensor.shape, flt_tensor.dtype, flt_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [41]:
rand_tens = torch.rand(3, 4)
rand_tens.shape, rand_tens.dtype, rand_tens.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [42]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [43]:
#multipy a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [44]:
tensor - 10

tensor([-9, -8, -7])

In [45]:
#PyTorch In Built Functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [47]:
#Matrix Multiplication

In [48]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [49]:
#Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [50]:
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.28 ms, sys: 89 µs, total: 2.37 ms
Wall time: 2.1 ms


In [52]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 212 µs, sys: 70 µs, total: 282 µs
Wall time: 225 µs


tensor(14)

In [53]:
## Common errors in deep learning -> shape errors when matrix multiplication
# 2 rules

In [54]:
tensor @ tensor # @ is the same as matmul


tensor(14)

In [55]:
#Shape rules (inner dimensions must match)
# (3, 2) (2, 3) works because 2 is the inner dimension of both matrices

torch.rand(3, 2).shape

torch.Size([3, 2])

In [56]:
torch.rand(3, 2)

tensor([[0.2995, 0.0055],
        [0.1497, 0.7176],
        [0.5705, 0.8219]])

In [57]:
torch.rand(2, 3) @ torch.rand(3, 2)

tensor([[0.7647, 1.3499],
        [0.6247, 0.9039]])

In [58]:
#This wont work torch.rand(2, 3) @ torch.rand(2, 3)

In [59]:
 # rule 2, the resulting matrix has the shape of the outer dimensions
 # (3, 2) * (2, 3) will have 3x3 matrix as a result
torch.matmul(torch.rand(3, 2), torch.rand(2, 4))

tensor([[0.6527, 0.4412, 0.4383, 0.1383],
        [1.0116, 0.6306, 0.6608, 0.2167],
        [0.9394, 0.7729, 0.6788, 0.1929]])

In [60]:
torch.matmul(torch.rand(3, 11), torch.rand(11, 4))

tensor([[2.3258, 2.1205, 3.5599, 2.7282],
        [2.9377, 2.5256, 3.4723, 2.5104],
        [3.4869, 2.9287, 4.5053, 3.0287]])

In [61]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [62]:
# torch.mm is short for torch.matmul
# matrix multiplication won't work on tensor_A and tensor_B because of shape errors
# We can fix this by manipulating a tensor by transposing it

tensor_B, tensor_B.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [63]:
tensor_B.T.shape

torch.Size([2, 3])

In [64]:
#with transpose, I can now multiply A and B
tensor_A @ tensor_B.T, torch.mm(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

In [65]:
# Tensor aggregation (min, max, mean sum)

#create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
# Find the min
torch.min(tensor_A @ tensor_B.T), x.min()

(tensor(27), tensor(0))

In [67]:
#Find the max
torch.max(torch.mm(tensor_A, tensor_B.T)), x.max()

(tensor(117), tensor(90))

In [68]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

#torch.mean(x) or x.mean() requires a float32 datatype to work, example of a datatype issue

(tensor(45.), tensor(45.))

In [69]:
#Find the sum
x.sum(), torch.sum(torch.matmul(tensor_A, tensor_B.T))

(tensor(450), tensor(612))

In [70]:
# Find positional minimum and maximum (what index has the min and what index has the max)
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [71]:
(tensor_A @ tensor_B.T).shape

torch.Size([3, 3])

In [72]:
# Reshaping, stacking, squeezing, and unsqueezing tensors

# Reshaping - reshape an input tensor to a defined shape
# View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
# Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
# Squeeze - removes all '1' dimensions from a tensor
# Unsqueeze - add a '1' dimension to a target tensor
# Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [73]:
# Let's create a tensor
import torch

In [74]:
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [75]:
# Add an extra dimensino
x_reshaped = x.reshape(3, 4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [76]:
# Change the view
z = x.view(4, 3)
z, z.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [77]:
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [78]:
# Changing z changes x because a view of a tensor shares the same memory as the original input

In [79]:
z[0][0] = 5
z, x

(tensor([[ 5.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [80]:
z[:, 0] = 1212
z, x

(tensor([[1212.,    2.,    3.],
         [1212.,    5.,    6.],
         [1212.,    8.,    9.],
         [1212.,   11.,   12.]]),
 tensor([1212.,    2.,    3., 1212.,    5.,    6., 1212.,    8.,    9., 1212.,
           11.,   12.]))

In [81]:
z.reshape(3, 4)
z, z.shape

(tensor([[1212.,    2.,    3.],
         [1212.,    5.,    6.],
         [1212.,    8.,    9.],
         [1212.,   11.,   12.]]),
 torch.Size([4, 3]))

In [82]:
x.reshape(3, 4)
x, x.shape

(tensor([1212.,    2.,    3., 1212.,    5.,    6., 1212.,    8.,    9., 1212.,
           11.,   12.]),
 torch.Size([12]))

In [83]:
z[:, 0] = 12
z, x

(tensor([[12.,  2.,  3.],
         [12.,  5.,  6.],
         [12.,  8.,  9.],
         [12., 11., 12.]]),
 tensor([12.,  2.,  3., 12.,  5.,  6., 12.,  8.,  9., 12., 11., 12.]))

In [84]:
x = z.reshape(3, 4)
x, x.shape

(tensor([[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]]),
 torch.Size([3, 4]))

In [85]:
z

tensor([[12.,  2.,  3.],
        [12.,  5.,  6.],
        [12.,  8.,  9.],
        [12., 11., 12.]])

In [86]:
x = z.view(3, 4)
x, x.shape

(tensor([[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]]),
 torch.Size([3, 4]))

In [87]:
z

tensor([[12.,  2.,  3.],
        [12.,  5.,  6.],
        [12.,  8.,  9.],
        [12., 11., 12.]])

In [88]:
x

tensor([[12.,  2.,  3., 12.],
        [ 5.,  6., 12.,  8.],
        [ 9., 12., 11., 12.]])

In [89]:
z

tensor([[12.,  2.,  3.],
        [12.,  5.,  6.],
        [12.,  8.,  9.],
        [12., 11., 12.]])

In [90]:
z = x.view(4, 3)
z, z.shape

(tensor([[12.,  2.,  3.],
         [12.,  5.,  6.],
         [12.,  8.,  9.],
         [12., 11., 12.]]),
 torch.Size([4, 3]))

In [91]:
x

tensor([[12.,  2.,  3., 12.],
        [ 5.,  6., 12.,  8.],
        [ 9., 12., 11., 12.]])

In [92]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]],

        [[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]],

        [[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]],

        [[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]]])

In [93]:
# torch.squeeze() remove all single dimensions from a tensor
squeeze = torch.zeros(2, 4, 1, 1)
squeeze

tensor([[[[0.]],

         [[0.]],

         [[0.]],

         [[0.]]],


        [[[0.]],

         [[0.]],

         [[0.]],

         [[0.]]]])

In [94]:
squeeze.shape

torch.Size([2, 4, 1, 1])

In [95]:
squeeze = squeeze.squeeze()

In [96]:
squeeze.shape

torch.Size([2, 4])

In [97]:
x.shape

torch.Size([3, 4])

In [98]:
x_stacked

tensor([[[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]],

        [[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]],

        [[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]],

        [[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]]])

In [99]:
x_stacked.shape

torch.Size([4, 3, 4])

In [100]:
x.shape

torch.Size([3, 4])

In [101]:
x.reshape(1, 12)

tensor([[12.,  2.,  3., 12.,  5.,  6., 12.,  8.,  9., 12., 11., 12.]])

In [102]:
x.shape

torch.Size([3, 4])

In [103]:
x = x.reshape(1, 12)

In [104]:
x.shape

torch.Size([1, 12])

In [105]:
x
x = x.squeeze()
x

tensor([12.,  2.,  3., 12.,  5.,  6., 12.,  8.,  9., 12., 11., 12.])

In [106]:
x.shape

torch.Size([12])

In [107]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
x_unsqueezed = x.unsqueeze(dim=0)
x_unsqueezed

tensor([[12.,  2.,  3., 12.,  5.,  6., 12.,  8.,  9., 12., 11., 12.]])

In [108]:
x = x.squeeze()
x = x.unsqueeze(dim=1)

In [109]:
x.shape

torch.Size([12, 1])

In [110]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
y = torch.rand(size=(224, 224, 3))
y.shape

torch.Size([224, 224, 3])

In [111]:
x = y.permute(2, 0, 1) # shifts 2->0 0->1 1->1
y.shape

torch.Size([224, 224, 3])

In [112]:
x.shape

torch.Size([3, 224, 224])

In [113]:
y[0, 0, 0] = 1212
y[0, 0, 0], x[0, 0, 0]

(tensor(1212.), tensor(1212.))

In [114]:
## Indexing (selecting data from tensors)

# indexing with pytorch is similar to indexing with NumPy

In [115]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [116]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [117]:
#Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [118]:
# or you can use
x[0, 0]

tensor([1, 2, 3])

In [119]:
x[0][1][2]

tensor(6)

In [120]:
x[0][2][2]

tensor(9)

In [121]:
# You can use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [122]:
x[0][:, 2]

tensor([3, 6, 9])

In [123]:
#Get all values of the 0th and 1st Dimensions, but only index1 of 2nd Dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [124]:
#Get all values of the 0th dimension, but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [125]:
# Get index 0 of the oth and 1st dimension, and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [126]:
x[0, 2, 2]

tensor(9)

In [127]:
#Pytorch tensors and NumPy

#NumPy is a popular scientific Python numerical computing library
#Thus, pytorch has functionality to interact with it

# data in NumPy, want a PyTorch tensor -> torch.from_numpy(ndarray)
# Pytorch tensor -> NumPy -> torch.Tensor.numpy()



In [128]:
#numpy array to tensor
#np is from NumPy
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7.]), array([1., 2., 3., 4., 5., 6., 7.]))

In [129]:
tensor.dtype

torch.float32

In [130]:
# What happens to tensor when you change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [131]:
tensor = torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [132]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [133]:
#Change the tensor, what happens to the array
tensor += 5
tensor, numpy_tensor

(tensor([6., 6., 6., 6., 6., 6., 6.]),
 array([6., 6., 6., 6., 6., 6., 6.], dtype=float32))

#Reproducability (Trying to take random out of random)

How NNs learns:

starts with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again . . .


To Reduce the randomness in NNs and Pytorch comes the concept of a random seed.

Essentially what the random sede does is flavor the randomness.


In [134]:
#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B


(tensor([[0.2117, 0.1851, 0.4341, 0.9745],
         [0.5362, 0.3800, 0.8278, 0.1190],
         [0.9950, 0.2063, 0.4676, 0.7448]]),
 tensor([[0.8641, 0.9931, 0.8708, 0.1030],
         [0.7526, 0.6039, 0.9394, 0.8054],
         [0.0500, 0.2283, 0.5059, 0.2605]]))

In [135]:
#Check for equality
random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [136]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [137]:
random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [138]:
# Running tensors and Pytorch obejcts on GPUS (and making faster computations)
#GPUs make faster computations on numbers thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything better



```
# This is formatted as code
```

### Getting a GPU

1. Easiest - Use Google Colab for a free GPU

2. Use your own GPU - takes a little bit of setup and requires a good GPU

3. Use Cloud Computing, GCP, AWS, Azure





In [139]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [140]:
#Check for GPU access with PyTorch
torch.cuda.is_available()

False

In [141]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu" # Run on GPU(s) if available, else run on CPU
device

'cpu'

In [142]:
#Count number of devices
torch.cuda.device_count()

0

In [143]:
##3. putting tensors (and models) on the GPU
#The reason we want our tensors/models on the GPu is because GPU results in faster computations

In [144]:
# create a tensor (default on cpu)

tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [145]:
# Moving tensor to gpu (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [146]:
### 4. Moving tensors back to the cpu

# If tensor is on GPU, can't transform it to NumPy
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu

tensor([1, 2, 3])

In [147]:
tensor_on_cpu.numpy()

array([1, 2, 3])

In [148]:
tensor_on_cpu.dtype

torch.int64

In [151]:
tensor_on_gpu[0] = 12
tensor_on_gpu

tensor([12,  2,  3])

In [152]:
tensor_on_cpu

tensor([12,  2,  3])

In [153]:
tensor_on_cpu[0] = 15
tensor_on_cpu

tensor([15,  2,  3])

In [154]:
tensor_on_gpu

tensor([15,  2,  3])