<a href="https://colab.research.google.com/github/pranavishal/Pytorch-CNN/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
print(torch.__version__)

2.4.1+cu121


In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [9]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

## Creating Tensors


In [10]:
# scalar, PyTorch tensors are created by torch.tensor(x)
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim # number of dimensions

0

In [12]:
scalar.item() # get tensor back as a python int

7

In [13]:
# vector

In [14]:
vector = torch.tensor([7, 7])
vector.ndim
vector.shape


torch.Size([2])

In [15]:
vector.ndim

1

In [16]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
MATRIX[0]

tensor([7, 8])

In [19]:
MATRIX[1]

tensor([ 9, 10])

In [20]:
##TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [22]:
TENSOR[0].shape

torch.Size([3, 3])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR2 = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]],
                        [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

In [25]:
TENSOR2.shape

torch.Size([2, 3, 3])



```
# This is formatted as code
```

### Random Tensors

Why Random tensors

random tensors are important because the way many neural networks learn is that they start with tensors full of randm numbers and then adjust those random numbers to better represent the data

start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers


In [26]:
# Create a random tensor of shape(3, 4)

random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.6598, 0.3064, 0.7055, 0.3518],
         [0.8148, 0.7319, 0.6463, 0.5549],
         [0.6537, 0.3518, 0.9121, 0.8640]],

        [[0.3113, 0.3847, 0.0534, 0.2443],
         [0.2797, 0.9619, 0.1188, 0.5375],
         [0.6438, 0.3594, 0.6254, 0.4601]]])

In [27]:
random_tensor.ndim

3

In [28]:
random_tensor.shape

torch.Size([2, 3, 4])

In [29]:
#Create a random tensor with similar shape ot an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [30]:
### Zeros and ones

In [31]:
# Create a tensor of all zeros
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zero * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [33]:
#all ones tensor

ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [35]:
random_tensor.dtype

torch.float32

In [36]:
# create a rang of tensors and tensors-like

#use torch.range()
one_to_ten = torch.arange(0, 10)
one_to_1000 = torch.arange(start=1, end=1000, step=92)

In [37]:
one_to_1000

tensor([  1,  93, 185, 277, 369, 461, 553, 645, 737, 829, 921])

In [38]:
#tensors like
ten_zeros = torch.zeros_like(input=one_to_1000)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
flt_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32, device=None, requires_grad=False)
#dtype what data type is the tensor made of
#device what device is your tensor on
#whether or not tot rack gradients with this tensors operations
flt_tensor

tensor([3., 6., 9.])

In [40]:
flt_tensor.dtype

torch.float32

In [41]:
#Tensor Datatypes
#tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning
#1. Tensors not right datatype
#2. Tensors not right shape
#3. Tensors not on the right device

In [42]:
float_16_tensor = flt_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [43]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [44]:
int_32_tensor * flt_tensor

tensor([ 9., 36., 81.])

In [45]:
flt_tensor

tensor([3., 6., 9.])

### Getting information from tensors (Tensor Attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [46]:
flt_tensor.shape, flt_tensor.dtype, flt_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [47]:
rand_tens = torch.rand(3, 4)
rand_tens.shape, rand_tens.dtype, rand_tens.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [48]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [49]:
#multipy a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [50]:
tensor - 10

tensor([-9, -8, -7])

In [51]:
#PyTorch In Built Functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [52]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [53]:
#Matrix Multiplication

In [54]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [55]:
#Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [56]:
torch.matmul(tensor, tensor)

tensor(14)

In [57]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.7 ms, sys: 0 ns, total: 1.7 ms
Wall time: 1.43 ms


In [58]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 278 µs, sys: 55 µs, total: 333 µs
Wall time: 286 µs


tensor(14)

In [59]:
## Common errors in deep learning -> shape errors when matrix multiplication
# 2 rules

In [60]:
tensor @ tensor # @ is the same as matmul


tensor(14)

In [61]:
#Shape rules (inner dimensions must match)
# (3, 2) (2, 3) works because 2 is the inner dimension of both matrices

torch.rand(3, 2).shape

torch.Size([3, 2])

In [62]:
torch.rand(3, 2)

tensor([[0.7403, 0.2895],
        [0.6173, 0.9278],
        [0.8237, 0.4422]])

In [63]:
torch.rand(2, 3) @ torch.rand(3, 2)

tensor([[0.3505, 0.4707],
        [1.2024, 0.8044]])

In [64]:
#This wont work torch.rand(2, 3) @ torch.rand(2, 3)

In [65]:
 # rule 2, the resulting matrix has the shape of the outer dimensions
 # (3, 2) * (2, 3) will have 3x3 matrix as a result
torch.matmul(torch.rand(3, 2), torch.rand(2, 4))

tensor([[0.4374, 0.8395, 1.3103, 1.1567],
        [0.3427, 0.7822, 1.1539, 1.0467],
        [0.2153, 0.6925, 0.9307, 0.8846]])

In [66]:
torch.matmul(torch.rand(3, 11), torch.rand(11, 4))

tensor([[3.4713, 3.4362, 2.4824, 3.4050],
        [2.5010, 2.7076, 1.8372, 2.8916],
        [3.8556, 3.9094, 3.2272, 3.7613]])

In [67]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [68]:
# torch.mm is short for torch.matmul
# matrix multiplication won't work on tensor_A and tensor_B because of shape errors
# We can fix this by manipulating a tensor by transposing it

tensor_B, tensor_B.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [69]:
tensor_B.T.shape

torch.Size([2, 3])

In [70]:
#with transpose, I can now multiply A and B
tensor_A @ tensor_B.T, torch.mm(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

In [71]:
# Tensor aggregation (min, max, mean sum)

#create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [72]:
# Find the min
torch.min(tensor_A @ tensor_B.T), x.min()

(tensor(27), tensor(0))

In [73]:
#Find the max
torch.max(torch.mm(tensor_A, tensor_B.T)), x.max()

(tensor(117), tensor(90))

In [74]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

#torch.mean(x) or x.mean() requires a float32 datatype to work, example of a datatype issue

(tensor(45.), tensor(45.))

In [75]:
#Find the sum
x.sum(), torch.sum(torch.matmul(tensor_A, tensor_B.T))

(tensor(450), tensor(612))

In [76]:
# Find positional minimum and maximum (what index has the min and what index has the max)
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [77]:
(tensor_A @ tensor_B.T).shape

torch.Size([3, 3])

In [78]:
# Reshaping, stacking, squeezing, and unsqueezing tensors

# Reshaping - reshape an input tensor to a defined shape
# View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
# Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
# Squeeze - removes all '1' dimensions from a tensor
# Unsqueeze - add a '1' dimension to a target tensor
# Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [79]:
# Let's create a tensor
import torch

In [86]:
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [89]:
# Add an extra dimensino
x_reshaped = x.reshape(3, 4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [97]:
# Change the view
z = x.view(4, 3)
z, z.shape

(tensor([[1212.,    2.,    3.],
         [   4.,    5.,    6.],
         [   7.,    8.,    9.],
         [  10.,   11.,   12.]]),
 torch.Size([4, 3]))

In [99]:
x, x.shape

(tensor([1212.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,   10.,
           11.,   12.]),
 torch.Size([12]))

In [100]:
# Changing z changes x because a view of a tensor shares the same memory as the original input

In [101]:
z[0][0] = 5
z, x

(tensor([[ 5.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [102]:
z[:, 0] = 1212
z, x

(tensor([[1212.,    2.,    3.],
         [1212.,    5.,    6.],
         [1212.,    8.,    9.],
         [1212.,   11.,   12.]]),
 tensor([1212.,    2.,    3., 1212.,    5.,    6., 1212.,    8.,    9., 1212.,
           11.,   12.]))

In [103]:
z.reshape(3, 4)
z, z.shape

(tensor([[1212.,    2.,    3.],
         [1212.,    5.,    6.],
         [1212.,    8.,    9.],
         [1212.,   11.,   12.]]),
 torch.Size([4, 3]))

In [104]:
x.reshape(3, 4)
x, x.shape

(tensor([1212.,    2.,    3., 1212.,    5.,    6., 1212.,    8.,    9., 1212.,
           11.,   12.]),
 torch.Size([12]))

In [105]:
z[:, 0] = 12
z, x

(tensor([[12.,  2.,  3.],
         [12.,  5.,  6.],
         [12.,  8.,  9.],
         [12., 11., 12.]]),
 tensor([12.,  2.,  3., 12.,  5.,  6., 12.,  8.,  9., 12., 11., 12.]))

In [106]:
x = z.reshape(3, 4)
x, x.shape

(tensor([[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]]),
 torch.Size([3, 4]))

In [107]:
z

tensor([[12.,  2.,  3.],
        [12.,  5.,  6.],
        [12.,  8.,  9.],
        [12., 11., 12.]])

In [108]:
x = z.view(3, 4)
x, x.shape

(tensor([[12.,  2.,  3., 12.],
         [ 5.,  6., 12.,  8.],
         [ 9., 12., 11., 12.]]),
 torch.Size([3, 4]))

In [109]:
z

tensor([[12.,  2.,  3.],
        [12.,  5.,  6.],
        [12.,  8.,  9.],
        [12., 11., 12.]])

In [110]:
x

tensor([[12.,  2.,  3., 12.],
        [ 5.,  6., 12.,  8.],
        [ 9., 12., 11., 12.]])

In [111]:
z

tensor([[12.,  2.,  3.],
        [12.,  5.,  6.],
        [12.,  8.,  9.],
        [12., 11., 12.]])

In [112]:
z = x.view(4, 3)
z, z.shape

(tensor([[12.,  2.,  3.],
         [12.,  5.,  6.],
         [12.,  8.,  9.],
         [12., 11., 12.]]),
 torch.Size([4, 3]))

In [113]:
x

tensor([[12.,  2.,  3., 12.],
        [ 5.,  6., 12.,  8.],
        [ 9., 12., 11., 12.]])

In [117]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[[12.,  2.,  3., 12.],
         [12.,  2.,  3., 12.],
         [12.,  2.,  3., 12.],
         [12.,  2.,  3., 12.]],

        [[ 5.,  6., 12.,  8.],
         [ 5.,  6., 12.,  8.],
         [ 5.,  6., 12.,  8.],
         [ 5.,  6., 12.,  8.]],

        [[ 9., 12., 11., 12.],
         [ 9., 12., 11., 12.],
         [ 9., 12., 11., 12.],
         [ 9., 12., 11., 12.]]])