<a href="https://colab.research.google.com/github/pranavishal/Pytorch-CNN/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.4.1+cu121


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
!nvidia-smi

Mon Oct 14 23:05:16 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0              46W / 400W |      2MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+--

## Introduction to Tensors

## Creating Tensors


In [ ]:
# scalar, PyTorch tensors are created by torch.tensor(x)
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # number of dimensions

0

In [ ]:
scalar.item() # get tensor back as a python int

7

In [ ]:
# vector

In [ ]:
vector = torch.tensor([7, 7])
vector.ndim
vector.shape


torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
##TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [ ]:
TENSOR[0].shape

torch.Size([3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR2 = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]],
                        [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

In [ ]:
TENSOR2.shape

torch.Size([2, 3, 3])