<a href="https://colab.research.google.com/github/pranavishal/Pytorch-CNN/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.4.1+cu121


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [4]:
!nvidia-smi

Tue Oct 15 19:58:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off | 00000000:00:04.0 Off |                    0 |
| N/A   31C    P0              47W / 400W |      2MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+--

## Introduction to Tensors

## Creating Tensors


In [5]:
# scalar, PyTorch tensors are created by torch.tensor(x)
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim # number of dimensions

0

In [7]:
scalar.item() # get tensor back as a python int

7

In [8]:
# vector

In [9]:
vector = torch.tensor([7, 7])
vector.ndim
vector.shape


torch.Size([2])

In [10]:
vector.ndim

1

In [11]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
##TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [17]:
TENSOR[0].shape

torch.Size([3, 3])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR2 = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]],
                        [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

In [20]:
TENSOR2.shape

torch.Size([2, 3, 3])



```
# This is formatted as code
```

### Random Tensors

Why Random tensors

random tensors are important because the way many neural networks learn is that they start with tensors full of randm numbers and then adjust those random numbers to better represent the data

start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers


In [23]:
# Create a random tensor of shape(3, 4)

random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.6944, 0.8394, 0.6567, 0.0964],
         [0.8556, 0.9819, 0.6059, 0.6927],
         [0.7304, 0.0511, 0.3463, 0.7247]],

        [[0.3495, 0.0551, 0.2379, 0.3144],
         [0.2844, 0.4018, 0.3488, 0.4251],
         [0.9001, 0.3868, 0.7660, 0.5089]]])

In [24]:
random_tensor.ndim

3

In [25]:
random_tensor.shape

torch.Size([2, 3, 4])

In [26]:
#Create a random tensor with similar shape ot an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [27]:
### Zeros and ones

In [29]:
# Create a tensor of all zeros
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
zero * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [31]:
#all ones tensor

ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

In [33]:
random_tensor.dtype

torch.float32

In [36]:
# create a rang of tensors and tensors-like

#use torch.range()
one_to_ten = torch.arange(0, 10)
one_to_1000 = torch.arange(start=1, end=1000, step=92)

In [37]:
one_to_1000

tensor([  1,  93, 185, 277, 369, 461, 553, 645, 737, 829, 921])

In [38]:
#tensors like
ten_zeros = torch.zeros_like(input=one_to_1000)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
flt_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32, device=None, requires_grad=False)
#dtype what data type is the tensor made of
#device what device is your tensor on
#whether or not tot rack gradients with this tensors operations
flt_tensor

tensor([3., 6., 9.])

In [56]:
flt_tensor.dtype

torch.float32

In [57]:
#Tensor Datatypes
#tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning
#1. Tensors not right datatype
#2. Tensors not right shape
#3. Tensors not on the right device

In [58]:
float_16_tensor = flt_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [59]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [60]:
int_32_tensor * flt_tensor

tensor([ 9., 36., 81.])

In [61]:
flt_tensor

tensor([3., 6., 9.])

### Getting information from tensors (Tensor Attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [65]:
flt_tensor.shape, flt_tensor.dtype, flt_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [66]:
rand_tens = torch.rand(3, 4)
rand_tens.shape, rand_tens.dtype, rand_tens.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [73]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [74]:
#multipy a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [75]:
tensor - 10

tensor([-9, -8, -7])

In [76]:
#PyTorch In Built Functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [77]:
torch.add(tensor, 10)

tensor([11, 12, 13])